State of the Publish Tree menu item should be refreshed whenever chil…
enonic-archive/app-contentstudio-old pull request #201
Opened 2018-06-08 10:33 UTC by edloidas

…d content is added or deleted #62

Added publish controls update in handlers for events that change children count.

2018-06-18 19:34 UTC, alansemenov requested changes

2018-06-18 19:34 UTC, alansemenov commented on src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
> +
I think it's wrong that ``updatePublishControls`` is called every time, even though the code inside won't be executed when ``childUpdated`` is ``false``. Also handlers for created content and deleted content are 100% identical. I suggest replacing the code below with this:
```Typescript
        const updatePublishControls = (childUpdated: boolean) => {
            this.fetchPersistedContent().then((content: Content) => {
                const isLeaf = !content.hasChildren();
                this.getContentWizardToolbarPublishControls().setLeafContent(isLeaf);
            }).catch(api.DefaultErrorHandler.handle).done();
        };

        const contentModifiedHandler = (data: any[]) => {
            const childUpdated = data.some(child => isChild(child.getPath()));
            if (childUpdated) {
                updatePublishControls(childUpdated);
            }
        };

        serverEvents.onContentCreated(contentModifiedHandler);
        serverEvents.onContentDeleted(contentModifiedHandler);
```

2018-06-19 09:14 UTC, edloidas commented on src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
> +
I've rebased this branch due to some changes in this and related repository. Also, I've modified the commit. I can agree with your point, except `data: any[]` type, since it's not type-safe and, originally, I was trying to make functions work with different types. But now I see, that we can make it much simpler with union types `data: Array<ContentSummaryAndCompareStatus | ContentServerChangeItem>`.

2018-06-19 13:08 UTC, alansemenov commented on src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
> +
Awesome! I didn't about this feature in Typescript...

2018-06-19 13:09 UTC, alansemenov approved these changes

2018-06-19 13:15 UTC, merged