Issue 243
enonic-archive/app-contentstudio-old pull request #259
Opened 2018-06-19 16:13 UTC by vbradnitski

2018-06-20 07:59 UTC, alansemenov requested changes

2018-06-20 07:59 UTC, alansemenov commented on src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
> +            return nearestSiteChanged || outboundDependencyUpdated;
With this approach we always make a request to check for outbound references, even when ``nearestSiteChanged`` is ``true`` when we don't really need to make this request.

What we need is this:
```Typescript
  const nearestSiteChanged = (isPageTemplateUpdated && isUpdatedItemUnderSite) || (isSiteUpdated && isItemUnderUpdatedSite);

  if (nearestSiteChanged) {
    return wemQ(true);
  }

  // 3. outbound dependency content has changed
  return this.isOutboundDependencyUpdated(content).then(outboundDependencyUpdated => outboundDependencyUpdated);

2018-06-20 08:50 UTC, alansemenov requested changes

2018-06-20 08:50 UTC, alansemenov commented on src/main/resources/assets/js/app/browse/ContentBrowsePanel.ts
> +            if (!previewRefreshed) {
Ok, this entire method is super-messy (not just the latest changes, but the old code as well).

Please do this:

1. Create a new method in ``Content`` class called ``isReferencedBy`` which will return a boolean promise. The method will take an array of either content ids or content objects and make a request to ContentQueryRequest (same as what now ``ContentQueryRequestHelper. anyIsOutboundDependency`` does).

2. Replace calls to ``ContentQueryRequestHelper. anyIsOutboundDependency`` with now beautifully looking calls to the new method, in both ``ContentBrowsePanel`` and ``ContentWizardPanel``:

``return previewItem.getModel().getContent().isReferencedBy(updatedContents.map(...));``

3. After that we no longer need ``ContentQueryRequestHelper``, so remove it.

4. Rename ``updatePreviewPanel`` to ``checkIfPreviewUpdateRequired`` and have it return a boolean promise of whether we need to update the preview (basically, return ``previewRefreshed``)

5. In this method remove all the calls to ``forcePreviewRerender``. It should only check whether we need to update the preview.

6. In ``handleContentUpdated``:
```Typescript
return this.doHandleContentUpdate(data).then((changed) => {
  this.checkIfPreviewUpdateRequired(data).then(previewUpdateRequired => previewUpdateRequired ? this.forcePreviewRerender() : null);
});
...
```

2018-06-20 08:51 UTC, alansemenov commented on src/main/resources/assets/js/app/browse/ContentBrowsePanel.ts
> +            if (!previewRefreshed) {
7... And if you'll be keeping the ``previewRefreshed`` const then rename it to ``previewRefreshRequired``

2018-06-21 15:54 UTC, vbradnitski commented
refactored.

2018-06-21 18:21 UTC, alansemenov commented
Good stuff, but you missed one requirement in the description. Page Editor should not be refreshed if the page has been changed. Now, if I made changes to the page and an outbound reference was updated then the page will be refreshed and I will lose my changes.

2018-06-22 19:49 UTC, alansemenov commented
Nize!

2018-06-22 19:49 UTC, alansemenov approved these changes

2018-06-22 19:49 UTC, merged