No confirmation when a fragment is about to be moved out of site #257
enonic-archive/app-contentstudio-old pull request #262
Opened 2018-06-21 08:41 UTC by ashklianko

-Issue is not about fragment at all. Bug was that filtered node was not found in content tree grid when trying to find content's parent until content is expanded in tree grid.
-Fixed by first trying to find node in tree grid and if not found fetching content's nearest site from backend.

2018-06-25 09:07 UTC, alansemenov requested changes
The original bug is fixed, but now I get a console error when trying to move a child item from under a site into a folder in the root, for example from Features into Large tree. 

![image](https://user-images.githubusercontent.com/11612490/41841200-f66e5e54-7867-11e8-86d0-2d50d681f7f3.png)

2018-06-25 13:55 UTC, ashklianko commented
Updated

2018-06-26 07:23 UTC, alansemenov approved these changes

2018-06-26 07:23 UTC, alansemenov commented
Perfect

2018-06-26 07:23 UTC, merged