Errors in browser console when an image is uploaded via DnD into HTML…
enonic-archive/app-contentstudio-old pull request #562
Opened 2018-11-22 11:24 UTC by ashklianko

… Area #548

-dnd images were not wrapped into figure element
-edge has FormData object without set() and get() functions, had to replace their usage with append()

2018-11-22 15:32 UTC, alansemenov requested changes

2018-11-22 15:32 UTC, alansemenov commented on src/main/resources/assets/js/app/inputtype/ui/text/HTMLAreaBuilder.ts
> +                this.replaceWith('<figure class="image">' +
Let's use string templates whenever possible, it looks much better than string concatenation.

```
`<img src="${upload.url}"`
```

2018-11-23 07:03 UTC, ashklianko commented on src/main/resources/assets/js/app/inputtype/ui/text/HTMLAreaBuilder.ts
> +                this.replaceWith('<figure class="image">' +
Ok! Will update

2018-11-23 16:12 UTC, alansemenov approved these changes

2018-11-23 16:13 UTC, merged